import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#fcdeb5",
        "on-secondary-fixed": "#0b1c30",
        secondary: "#505f76",
        "tertiary-container": "#271901",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed": "#271901",
        "secondary-fixed-dim": "#b7c8e1",
        "outline-variant": "#c6c6cd",
        tertiary: "#000000",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        outline: "#76777d",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191c1e",
        "primary-fixed": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary-container": "#98805d",
        "on-primary-container": "#7c839b",
        primary: "#000000",
        background: "#f7f9fb",
        "surface-tint": "#565e74",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "secondary-fixed": "#d3e4fe",
        "tertiary-fixed-dim": "#dec29a",
        "on-secondary-container": "#54647a",
        "inverse-primary": "#bec6e0",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-high": "#e6e8ea",
        "on-surface-variant": "#45464d",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "secondary-container": "#d0e1fb",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed-variant": "#574425",
        "on-primary-fixed-variant": "#3f465c",
        surface: "#f7f9fb",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#131b2e",
        "primary-fixed-dim": "#bec6e0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        lg: "24px",
        sm: "8px",
        md: "16px",
        margin: "24px",
        base: "4px",
        xl: "32px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-caps": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
